version: 1.0.{build}

configuration: Debug

platform: Any CPU

build:

  project: NetGears.sln

  verbosity: minimal

notifications:

- provider: Email

  to:

  - syleze.contact@gmail.com

  subject: '[NetGears] appveyor build status'

  on_build_success: true

  on_build_failure: true

  on_build_status_changed: true
